version: '3.4'

services:
  elasticsearch:
    build:
      context: elasticsearch/
    restart: always
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      ES_JAVA_OPTS: -Xmx256m -Xms256m
    networks:
      - elk

  logstash:
    build:
      context: logstash/
    restart: always
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - 5000:5000
      - 5500:5500
    environment:
      LS_JAVA_OPTS: -Xmx256m -Xms256m
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
    restart: always
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - 5601:5601
    networks:
      - elk
    depends_on:
      - elasticsearch

  filebeat:
    build:
      context: filebeat/
    restart: always
    command: filebeat -e -strict.perms=false
    volumes:
      - ./filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./logs:/logs:ro
    networks:
      - elk
    depends_on:
      - logstash

  app:
    build:
      context: logs-generator/
    restart: always
    volumes:
      - ./logs:/logs-generator/bin/logs
    networks:
      - elk
    depends_on:
      - kibana

networks:
  elk:
    driver: bridge
